# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(600, 630)
        mainWindow.setMinimumSize(QtCore.QSize(600, 630))
        mainWindow.setMaximumSize(QtCore.QSize(600, 630))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/zk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("")
        mainWindow.setIconSize(QtCore.QSize(25, 24))
        mainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setStyleSheet(".QWidget{\n"
"    \n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"border-bottom-left-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-2, -14, 606, 661))
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"    font: 75 14pt \"微软雅黑\";\n"
"    border:none;\n"
"    alignment: center;\n"
"}\n"
"QTabBar::tab {\n"
"    font: 75 13pt \"微软雅黑\";        \n"
"    color: rgb(255, 255, 255);\n"
"    width:160px;                    \n"
"    height:18;                     \n"
"    margin-top:5px;    \n"
"    background:rgb(150, 75, 112);\n"
"    padding:20px;\n"
"    margin-right:0px;\n"
"    border-right:1px solid qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"           stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"\n"
"    \n"
"}\n"
"QTabWidget::pane {\n"
"    border: 0px solid black;\n"
"    border-radius:7px;\n"
"    position: absolute;\n"
"    top: -1em;\n"
"}    \n"
"QTabBar::tab:selected{\n"
" background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"           stop:0 rgb(150, 75, 112),stop:0.5 rgb(200, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
" \n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setIconSize(QtCore.QSize(45, 45))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.disconnect = QtWidgets.QPushButton(self.tab_2)
        self.disconnect.setGeometry(QtCore.QRect(310, 400, 71, 31))
        self.disconnect.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.disconnect.setObjectName("disconnect")
        self.connnect = QtWidgets.QPushButton(self.tab_2)
        self.connnect.setGeometry(QtCore.QRect(200, 400, 71, 31))
        self.connnect.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.connnect.setObjectName("connnect")
        self.label_57 = QtWidgets.QLabel(self.tab_2)
        self.label_57.setGeometry(QtCore.QRect(220, 110, 169, 33))
        self.label_57.setStyleSheet("background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"           stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Arial Rounded MT Bold\";\n"
"border: 0.5px solid ;\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(190, 170, 211, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.port = QtWidgets.QComboBox(self.layoutWidget)
        self.port.setMinimumSize(QtCore.QSize(0, 25))
        self.port.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.port.setObjectName("port")
        self.port.addItem("")
        self.port.addItem("")
        self.port.addItem("")
        self.port.addItem("")
        self.port.addItem("")
        self.gridLayout.addWidget(self.port, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.car_x = QtWidgets.QLineEdit(self.layoutWidget)
        self.car_x.setObjectName("car_x")
        self.gridLayout.addWidget(self.car_x, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.car_y = QtWidgets.QLineEdit(self.layoutWidget)
        self.car_y.setObjectName("car_y")
        self.gridLayout.addWidget(self.car_y, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.model = QtWidgets.QComboBox(self.layoutWidget)
        self.model.setMinimumSize(QtCore.QSize(0, 25))
        self.model.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.model.setObjectName("model")
        self.model.addItem("")
        self.model.addItem("")
        self.gridLayout.addWidget(self.model, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setStyleSheet("background-color:transparent; \n"
"color: black;\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.video = QtWidgets.QComboBox(self.layoutWidget)
        self.video.setMinimumSize(QtCore.QSize(0, 25))
        self.video.setStyleSheet("QComboBox{\n"
"font: 75 9pt \"微软雅黑\";\n"
"border:none;\n"
"background-color:transparent ;\n"
"border-bottom:1px solid rgb(150, 75, 112)\n"
"}\n"
"QComboBox::down-arrow{\n"
"image: url(:/icon/arrow_t.png);\n"
" width:15px;\n"
" height:20px;\n"
"}\n"
"QComboBox::drop-down{\n"
"background-color:transparent;\n"
"width:20px;\n"
"height:15px; \n"
"}\n"
"")
        self.video.setObjectName("video")
        self.video.addItem("")
        self.video.addItem("")
        self.video.addItem("")
        self.video.addItem("")
        self.video.addItem("")
        self.video.addItem("")
        self.gridLayout.addWidget(self.video, 4, 1, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/sz_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.claer = QtWidgets.QPushButton(self.tab)
        self.claer.setGeometry(QtCore.QRect(530, 20, 60, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.claer.setFont(font)
        self.claer.setStyleSheet("QPushButton{  \n"
"    border-radius:3px ;\n"
"    font: 75 10pt \"微软雅黑\";    \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,stop:0 rgb(150, 75, 112),stop:0.5 rgb(255, 255, 255),stop:1 rgb(150, 75, 112));\n"
"    color: rgb(0,0,0);    \n"
"    border: 0.5px solid ;\n"
"}\n"
"\n"
"QPushButton:hover{  \n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(63, 63, 63);\n"
"}")
        self.claer.setObjectName("claer")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 61, 18))
        self.label_2.setStyleSheet("background-color: rgb(239, 239, 239);\n"
"font: 75 11pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 470, 281, 16))
        self.groupBox.setStyleSheet("border:none")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.current_rec = QtWidgets.QListWidget(self.tab)
        self.current_rec.setGeometry(QtCore.QRect(5, 51, 591, 511))
        self.current_rec.setObjectName("current_rec")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/js.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget_5 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(430, 390, 161, 171))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.up_left_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.up_left_2.setMinimumSize(QtCore.QSize(48, 48))
        self.up_left_2.setMaximumSize(QtCore.QSize(48, 48))
        self.up_left_2.setStyleSheet("QPushButton {background-image: url(images//up_left.png);background-position: center;}")
        self.up_left_2.setText("")
        self.up_left_2.setObjectName("up_left_2")
        self.gridLayout_2.addWidget(self.up_left_2, 0, 0, 1, 1)
        self.up_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.up_2.setMinimumSize(QtCore.QSize(48, 48))
        self.up_2.setMaximumSize(QtCore.QSize(48, 48))
        self.up_2.setStyleSheet("background-image:url(images//up.png);background-position: center;")
        self.up_2.setText("")
        self.up_2.setObjectName("up_2")
        self.gridLayout_2.addWidget(self.up_2, 0, 1, 1, 1)
        self.up_right_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.up_right_2.setMinimumSize(QtCore.QSize(48, 48))
        self.up_right_2.setMaximumSize(QtCore.QSize(48, 48))
        self.up_right_2.setStyleSheet("QPushButton {background-image: url(images//up_right.png);background-position: center;}")
        self.up_right_2.setText("")
        self.up_right_2.setObjectName("up_right_2")
        self.gridLayout_2.addWidget(self.up_right_2, 0, 2, 1, 1)
        self.left_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.left_2.setMinimumSize(QtCore.QSize(48, 48))
        self.left_2.setMaximumSize(QtCore.QSize(48, 48))
        self.left_2.setStyleSheet("QPushButton {background-image: url(images//left.png);background-position: center;}")
        self.left_2.setText("")
        self.left_2.setObjectName("left_2")
        self.gridLayout_2.addWidget(self.left_2, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.pushButton_7.setMinimumSize(QtCore.QSize(48, 48))
        self.pushButton_7.setMaximumSize(QtCore.QSize(48, 48))
        self.pushButton_7.setStyleSheet("QPushButton {background-image: url(images//auto.png);background-position: center;}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.right_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.right_2.setMinimumSize(QtCore.QSize(48, 48))
        self.right_2.setMaximumSize(QtCore.QSize(48, 48))
        self.right_2.setStyleSheet("QPushButton {background-image: url(images//right.png);background-position: center;}")
        self.right_2.setText("")
        self.right_2.setObjectName("right_2")
        self.gridLayout_2.addWidget(self.right_2, 1, 2, 1, 1)
        self.down_left_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.down_left_2.setMinimumSize(QtCore.QSize(48, 48))
        self.down_left_2.setMaximumSize(QtCore.QSize(48, 48))
        self.down_left_2.setStyleSheet("QPushButton {background-image: url(images//down_left.png);background-position: center;}")
        self.down_left_2.setText("")
        self.down_left_2.setObjectName("down_left_2")
        self.gridLayout_2.addWidget(self.down_left_2, 2, 0, 1, 1)
        self.down_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.down_2.setMinimumSize(QtCore.QSize(48, 48))
        self.down_2.setMaximumSize(QtCore.QSize(48, 48))
        self.down_2.setStyleSheet("QPushButton {background-image: url(images//down.png);background-position: center;}")
        self.down_2.setText("")
        self.down_2.setObjectName("down_2")
        self.gridLayout_2.addWidget(self.down_2, 2, 1, 1, 1)
        self.down_right_2 = QtWidgets.QPushButton(self.layoutWidget_5)
        self.down_right_2.setMinimumSize(QtCore.QSize(48, 48))
        self.down_right_2.setMaximumSize(QtCore.QSize(48, 48))
        self.down_right_2.setStyleSheet("QPushButton {background-image: url(images//down_right.png);background-position: center;}")
        self.down_right_2.setText("")
        self.down_right_2.setObjectName("down_right_2")
        self.gridLayout_2.addWidget(self.down_right_2, 2, 2, 1, 1)
        self.layoutWidget_6 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_6.setGeometry(QtCore.QRect(40, 410, 41, 131))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.layoutWidget_7 = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget_7.setGeometry(QtCore.QRect(120, 410, 251, 131))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.model_2 = QtWidgets.QLabel(self.layoutWidget_7)
        self.model_2.setText("")
        self.model_2.setAlignment(QtCore.Qt.AlignCenter)
        self.model_2.setObjectName("model_2")
        self.verticalLayout_4.addWidget(self.model_2)
        self.speed_2 = QtWidgets.QLabel(self.layoutWidget_7)
        self.speed_2.setText("")
        self.speed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_2.setObjectName("speed_2")
        self.verticalLayout_4.addWidget(self.speed_2)
        self.position_2 = QtWidgets.QLabel(self.layoutWidget_7)
        self.position_2.setText("")
        self.position_2.setAlignment(QtCore.Qt.AlignCenter)
        self.position_2.setObjectName("position_2")
        self.verticalLayout_4.addWidget(self.position_2)
        self.cor_2 = QtWidgets.QLabel(self.layoutWidget_7)
        self.cor_2.setText("")
        self.cor_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cor_2.setObjectName("cor_2")
        self.verticalLayout_4.addWidget(self.cor_2)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(0, 340, 461, 31))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.frame_4 = QtWidgets.QFrame(self.tab_4)
        self.frame_4.setGeometry(QtCore.QRect(10, 20, 591, 351))
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(5000, 5000))
        self.frame_4.setStyleSheet(".QFrame{\n"
"   background-color: rgb(255, 255, 255);\n"
"   border:0px;\n"
"   border-radius:12px;\n"
"   color:white;\n"
"   border: 8px solid qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                stop:0 rgb(0, 179, 87),stop:0.5 rgb(50, 149, 0),stop:1 rgb(0, 179, 87));\n"
"   border-color: rgb(150, 75, 112);\n"
"   }\n"
"QLineEdit{\n"
"border:none;\n"
"color:rgb(150, 75, 112);\n"
"color: rgb(150, 75, 112);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.car_list_2 = QtWidgets.QListWidget(self.frame_4)
        self.car_list_2.setGeometry(QtCore.QRect(20, 60, 291, 271))
        self.car_list_2.setObjectName("car_list_2")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(40, 30, 91, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.Refresh_3 = QtWidgets.QPushButton(self.frame_4)
        self.Refresh_3.setGeometry(QtCore.QRect(210, 30, 81, 21))
        self.Refresh_3.setObjectName("Refresh_3")
        self.car_list_3 = QtWidgets.QListWidget(self.frame_4)
        self.car_list_3.setGeometry(QtCore.QRect(370, 60, 191, 271))
        self.car_list_3.setObjectName("car_list_3")
        self.Refresh_4 = QtWidgets.QPushButton(self.frame_4)
        self.Refresh_4.setGeometry(QtCore.QRect(510, 30, 51, 21))
        self.Refresh_4.setObjectName("Refresh_4")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(370, 30, 91, 20))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/bz_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon3, "")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(150, 75, 112);")
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actiondakaipeizhiwenjian = QtWidgets.QAction(mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Picturere/Picture/right2.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actiondakaipeizhiwenjian.setIcon(icon4)
        self.actiondakaipeizhiwenjian.setObjectName("actiondakaipeizhiwenjian")
        self.actiondakaipeizhiwenjian_2 = QtWidgets.QAction(mainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Picturere/Picture/square_add.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actiondakaipeizhiwenjian_2.setIcon(icon5)
        self.actiondakaipeizhiwenjian_2.setObjectName("actiondakaipeizhiwenjian_2")
        self.actionlianjixieshou_I = QtWidgets.QAction(mainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Basilisk.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionlianjixieshou_I.setIcon(icon6)
        self.actionlianjixieshou_I.setObjectName("actionlianjixieshou_I")
        self.actionlianPlc_T = QtWidgets.QAction(mainWindow)
        self.actionlianPlc_T.setIcon(icon6)
        self.actionlianPlc_T.setPriority(QtWidgets.QAction.HighPriority)
        self.actionlianPlc_T.setObjectName("actionlianPlc_T")
        self.actioncaozuoPLC_O = QtWidgets.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Djinni.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actioncaozuoPLC_O.setIcon(icon7)
        self.actioncaozuoPLC_O.setObjectName("actioncaozuoPLC_O")
        self.actionCanshushezhi_P = QtWidgets.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Sorceress.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionCanshushezhi_P.setIcon(icon8)
        self.actionCanshushezhi_P.setObjectName("actionCanshushezhi_P")
        self.actionjinzhi_N = QtWidgets.QAction(mainWindow)
        self.actionjinzhi_N.setObjectName("actionjinzhi_N")
        self.actionxunyu_Y = QtWidgets.QAction(mainWindow)
        self.actionxunyu_Y.setObjectName("actionxunyu_Y")
        self.actiondakaishujukufuwuqi = QtWidgets.QAction(mainWindow)
        self.actiondakaishujukufuwuqi.setObjectName("actiondakaishujukufuwuqi")
        self.actionguanbishujukufuwuqi = QtWidgets.QAction(mainWindow)
        self.actionguanbishujukufuwuqi.setObjectName("actionguanbishujukufuwuqi")
        self.actionlianjieshujuku_L = QtWidgets.QAction(mainWindow)
        self.actionlianjieshujuku_L.setObjectName("actionlianjieshujuku_L")
        self.actionduankaishujuku_C = QtWidgets.QAction(mainWindow)
        self.actionduankaishujuku_C.setObjectName("actionduankaishujuku_C")
        self.actionpanduan_Y = QtWidgets.QAction(mainWindow)
        self.actionpanduan_Y.setObjectName("actionpanduan_Y")
        self.actionbupanduan_N = QtWidgets.QAction(mainWindow)
        self.actionbupanduan_N.setObjectName("actionbupanduan_N")
        self.actionyicitongguo_O = QtWidgets.QAction(mainWindow)
        self.actionyicitongguo_O.setObjectName("actionyicitongguo_O")
        self.actionchankandangqianzhuangtai_S = QtWidgets.QAction(mainWindow)
        self.actionchankandangqianzhuangtai_S.setObjectName("actionchankandangqianzhuangtai_S")
        self.actionjilu_R = QtWidgets.QAction(mainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Valkyrie.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionjilu_R.setIcon(icon9)
        self.actionjilu_R.setObjectName("actionjilu_R")
        self.actionshegnchengdejieguo_G = QtWidgets.QAction(mainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Earth Elemental.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionshegnchengdejieguo_G.setIcon(icon10)
        self.actionshegnchengdejieguo_G.setObjectName("actionshegnchengdejieguo_G")
        self.actionpeizhicanshulujing_M = QtWidgets.QAction(mainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Picturere/Picture/rightdown.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionpeizhicanshulujing_M.setIcon(icon11)
        self.actionpeizhicanshulujing_M.setObjectName("actionpeizhicanshulujing_M")
        self.actionzhegnchangshenchan_N = QtWidgets.QAction(mainWindow)
        self.actionzhegnchangshenchan_N.setObjectName("actionzhegnchangshenchan_N")
        self.actionshouliaomoshi_C = QtWidgets.QAction(mainWindow)
        self.actionshouliaomoshi_C.setObjectName("actionshouliaomoshi_C")
        self.actionshi_Y = QtWidgets.QAction(mainWindow)
        self.actionshi_Y.setObjectName("actionshi_Y")
        self.actionfou_N = QtWidgets.QAction(mainWindow)
        self.actionfou_N.setObjectName("actionfou_N")
        self.actionzhongkongjima_P = QtWidgets.QAction(mainWindow)
        self.actionzhongkongjima_P.setObjectName("actionzhongkongjima_P")
        self.actionchongxinsaoma_I = QtWidgets.QAction(mainWindow)
        self.actionchongxinsaoma_I.setObjectName("actionchongxinsaoma_I")
        self.actionqiyong_U = QtWidgets.QAction(mainWindow)
        self.actionqiyong_U.setObjectName("actionqiyong_U")
        self.actionjinyong_N = QtWidgets.QAction(mainWindow)
        self.actionjinyong_N.setObjectName("actionjinyong_N")
        self.actionchakanbangzhu_V = QtWidgets.QAction(mainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Iconn/Icon/Wizard.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        self.actionchakanbangzhu_V.setIcon(icon12)
        self.actionchakanbangzhu_V.setObjectName("actionchakanbangzhu_V")
        self.actioncaozuojixies = QtWidgets.QAction(mainWindow)
        self.actioncaozuojixies.setObjectName("actioncaozuojixies")
        self.actionxunhuanjieshoujxs = QtWidgets.QAction(mainWindow)
        self.actionxunhuanjieshoujxs.setObjectName("actionxunhuanjieshoujxs")
        self.actionshoudongPLC = QtWidgets.QAction(mainWindow)
        self.actionshoudongPLC.setObjectName("actionshoudongPLC")
        self.actionmianbanxieru = QtWidgets.QAction(mainWindow)
        self.actionmianbanxieru.setObjectName("actionmianbanxieru")
        self.actiondakaiwangkou = QtWidgets.QAction(mainWindow)
        self.actiondakaiwangkou.setObjectName("actiondakaiwangkou")
        self.actionwangkoufasong = QtWidgets.QAction(mainWindow)
        self.actionwangkoufasong.setObjectName("actionwangkoufasong")
        self.actionjiechuPlc = QtWidgets.QAction(mainWindow)
        self.actionjiechuPlc.setObjectName("actionjiechuPlc")

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "    终端"))
        self.disconnect.setText(_translate("mainWindow", "删除"))
        self.connnect.setText(_translate("mainWindow", "放置"))
        self.label_57.setText(_translate("mainWindow", "放置小车"))
        self.label_7.setText(_translate("mainWindow", "小车编号"))
        self.port.setItemText(0, _translate("mainWindow", "car_1"))
        self.port.setItemText(1, _translate("mainWindow", "car_2"))
        self.port.setItemText(2, _translate("mainWindow", "car_3"))
        self.port.setItemText(3, _translate("mainWindow", "car_4"))
        self.port.setItemText(4, _translate("mainWindow", "car_5"))
        self.label_8.setText(_translate("mainWindow", "X方位坐标"))
        self.label_9.setText(_translate("mainWindow", "Y方位坐标"))
        self.label_10.setText(_translate("mainWindow", "小车模式"))
        self.model.setItemText(0, _translate("mainWindow", "手动模式"))
        self.model.setItemText(1, _translate("mainWindow", "自动巡航"))
        self.label_11.setText(_translate("mainWindow", "摄像头"))
        self.video.setItemText(0, _translate("mainWindow", "images1"))
        self.video.setItemText(1, _translate("mainWindow", "images2"))
        self.video.setItemText(2, _translate("mainWindow", "images3"))
        self.video.setItemText(3, _translate("mainWindow", "images4"))
        self.video.setItemText(4, _translate("mainWindow", "images5"))
        self.video.setItemText(5, _translate("mainWindow", "images6"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "初始化"))
        self.claer.setText(_translate("mainWindow", "清屏"))
        self.label_2.setText(_translate("mainWindow", "实时通讯"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "通讯信息"))
        self.label_12.setText(_translate("mainWindow", "模式"))
        self.label_13.setText(_translate("mainWindow", "速度"))
        self.label_14.setText(_translate("mainWindow", "坐标"))
        self.label_15.setText(_translate("mainWindow", "方位角"))
        self.label_16.setText(_translate("mainWindow", "当前小车状态信息"))
        self.label_17.setText(_translate("mainWindow", "本地指令讯息"))
        self.Refresh_3.setText(_translate("mainWindow", "清 除"))
        self.Refresh_4.setText(_translate("mainWindow", "刷新"))
        self.label_18.setText(_translate("mainWindow", "待机小车列表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("mainWindow", "遥控"))
        self.actiondakaipeizhiwenjian.setText(_translate("mainWindow", "查看配置文件内容(&L)"))
        self.actiondakaipeizhiwenjian_2.setText(_translate("mainWindow", "打开配置文件(&C)"))
        self.actionlianjixieshou_I.setText(_translate("mainWindow", "与机械手通讯(&I)"))
        self.actionlianjixieshou_I.setIconText(_translate("mainWindow", "与机械手通讯(I)"))
        self.actionlianjixieshou_I.setToolTip(_translate("mainWindow", "连接机械手(I)"))
        self.actionlianPlc_T.setText(_translate("mainWindow", "打开PLC串口(&T)"))
        self.actioncaozuoPLC_O.setText(_translate("mainWindow", "操作PLC(&O)"))
        self.actionCanshushezhi_P.setText(_translate("mainWindow", "参数设置(&P)"))
        self.actionjinzhi_N.setText(_translate("mainWindow", "禁止(&N)"))
        self.actionjinzhi_N.setIconText(_translate("mainWindow", "禁止(N)"))
        self.actionxunyu_Y.setText(_translate("mainWindow", "允许(&Y)"))
        self.actiondakaishujukufuwuqi.setText(_translate("mainWindow", "打开数据库服务器"))
        self.actionguanbishujukufuwuqi.setText(_translate("mainWindow", "关闭数据库服务器"))
        self.actionlianjieshujuku_L.setText(_translate("mainWindow", "连接数据库(&L)"))
        self.actionduankaishujuku_C.setText(_translate("mainWindow", "打开数据库(&C)"))
        self.actionpanduan_Y.setText(_translate("mainWindow", "判断(&Y)"))
        self.actionbupanduan_N.setText(_translate("mainWindow", "不判断(&N)"))
        self.actionyicitongguo_O.setText(_translate("mainWindow", "一次通过(&O)"))
        self.actionchankandangqianzhuangtai_S.setText(_translate("mainWindow", "查看当前状态(&S)"))
        self.actionjilu_R.setText(_translate("mainWindow", "记录(&R)"))
        self.actionshegnchengdejieguo_G.setText(_translate("mainWindow", "生成的结果(&G)"))
        self.actionpeizhicanshulujing_M.setText(_translate("mainWindow", "配置参数路径(&M)"))
        self.actionzhegnchangshenchan_N.setText(_translate("mainWindow", "正常生成(&N)"))
        self.actionshouliaomoshi_C.setText(_translate("mainWindow", "收料模式(&C)"))
        self.actionshi_Y.setText(_translate("mainWindow", "是(&Y)"))
        self.actionfou_N.setText(_translate("mainWindow", "否(&N)"))
        self.actionzhongkongjima_P.setText(_translate("mainWindow", "中控记码(&P)"))
        self.actionchongxinsaoma_I.setText(_translate("mainWindow", "重新扫码(&I)"))
        self.actionqiyong_U.setText(_translate("mainWindow", "启用(&U)"))
        self.actionjinyong_N.setText(_translate("mainWindow", "禁用(&N)"))
        self.actionchakanbangzhu_V.setText(_translate("mainWindow", "查看帮助(&V)"))
        self.actioncaozuojixies.setText(_translate("mainWindow", "操作机械手"))
        self.actionxunhuanjieshoujxs.setText(_translate("mainWindow", "循环接收JXS"))
        self.actionshoudongPLC.setText(_translate("mainWindow", "手动触发PLC"))
        self.actionmianbanxieru.setText(_translate("mainWindow", "面板信息写入"))
        self.actiondakaiwangkou.setText(_translate("mainWindow", "开启服务器"))
        self.actionwangkoufasong.setText(_translate("mainWindow", "网口发送"))
        self.actionjiechuPlc.setText(_translate("mainWindow", "解除PLC报警"))
import ico_rc
